from player import Player

# sorcerer = Player(15,25,"gnomo","hey ho! hey ho!")
#gnomo = Player(15,25,"gnomo")
gnomo = Player(hit_points=15,mana=25,vocacion="gnomo",hechizo="Utevo Lux")
print("\nEl gnomo tiene:")
print(gnomo.hit_points)
print(gnomo.mana)
print(gnomo.vocacion)
print(gnomo.lanzar_hechizo())

sorcerer = Player(hit_points=40,mana=80,vocacion="sorcerer",hechizo="wing guardium leviousa")
print("\nEl Sorcerer tiene:")
print(sorcerer.hit_points)
print(sorcerer.mana)
print(sorcerer.vocacion)
print(sorcerer.lanzar_hechizo())

knight = Player(hit_points=80,mana=20,vocacion="caballero",hechizo="expelermus")
print("\nEl Knight tiene:")
print(knight.hit_points)
print(knight.mana)
print(knight.vocacion)
print(knight.lanzar_hechizo())

paladin = Player(hit_points=100,mana=40,vocacion="paladin",hechizo="Expectro patronus")
print("\nEl paladin tiene:")
print(paladin.hit_points)
print(paladin.mana)
print(paladin.vocacion)
print(paladin.lanzar_hechizo())

druid = Player(hit_points=60,mana=100,vocacion="druida",hechizo="exori")
print("\nEl druid tiene:")
print(druid.hit_points)
print(druid.mana)
print(druid.vocacion)
print(druid.lanzar_hechizo())