import player

# sorcerer = Player(15,25,"gnomo","hey ho! hey ho!")
#gnomo = Player(15,25,"gnomo")
gnomo = player.Player(hit_points=15,mana=25)
print("\nEl gnomo tiene:")
print(gnomo.hit_points)
print(gnomo.mana)
print(gnomo.vocacion)
print(gnomo.lanzar_hechizo())
print(gnomo.velocidad_movimiento)

sorcerer = player.Sorcerer(hit_points=40,mana=80)
print("\nEl Sorcerer tiene:")
print(sorcerer.hit_points)
print(sorcerer.mana)
print(sorcerer.vocacion)
print(sorcerer.lanzar_hechizo())
print(sorcerer.velocidad_movimiento)

knight = player.Knight(hit_points=80,mana=20)
print("\nEl Knight tiene:")
print(knight.hit_points)
print(knight.mana)
print(knight.vocacion)
print(knight.lanzar_hechizo())
print(knight.velocidad_movimiento)

paladin = player.Paladin(hit_points=100,mana=40)
print("\nEl paladin tiene:")
print(paladin.hit_points)
print(paladin.mana)
print(paladin.vocacion)
print(paladin.lanzar_hechizo())
print(paladin.velocidad_movimiento)

druid = player.Druida(hit_points=60,mana=100)
print("\nEl druid tiene:")
print(druid.hit_points)
print(druid.mana)
print(druid.vocacion)
print(druid.lanzar_hechizo())
print(druid.velocidad_movimiento)